django_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from rest_framework import routers
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from users.views import UserViewSet, HomeViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'homes', HomeViewSet)

urlpatterns = [
    path('', include("users.urls"), name="users"),
    url(r'^admin/', admin.site.urls),
    path('api/v0/', include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from .views import UserView, HomeView, HomesView, UserDetailView, UserUpdateView, HomeUpdateView, ImageListView


urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('users', UserView.as_view(), name='users'),
    path('users/<int:pk>', UserUpdateView.as_view(), name='users-update'),
    path('homes/<int:pk>', HomeUpdateView.as_view(), name='homes-update'),
    path('homes', HomesView.as_view(), name='homes'),
    path('homes/<int:user_id>', HomesView.as_view(), name='user_homes'),
    path('images/<int:home_id>', ImageListView.as_view(), name='home_images'),
    path('<slug:slug>', UserDetailView.as_view(), name='user-detail'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import ugettext_lazy as _


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('first_name', "admin")
        extra_fields.setdefault('last_name', "admin")
        extra_fields.setdefault('age', "100")
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    age = models.PositiveIntegerField()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Home(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    location = models.CharField(max_length=128)
    land_sqm = models.FloatField()
    place_sqm = models.FloatField()
    bedrooms = models.PositiveIntegerField()

    def __str__(self):
        return "{} : {}".format(self.user.email,  self.title)


class HomeImage(models.Model):
    home = models.ForeignKey(Home, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')

users/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import User, Home, HomeImage


class UserForm(forms.ModelForm):
    class Meta:
        fields = "first_name", "last_name", "email", "age"
        model = User

class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='image')

    class Meta:
        model = HomeImage
        fields = ['image',]


class HomeForm(forms.ModelForm):

    class Meta:
        fields = "__all__"
        model = Home

imageformset = inlineformset_factory(Home, HomeImage, form=ImageForm, can_delete=True, exclude=[], extra=1)

users/views.py
from django.urls import reverse
from django.views.generic import ListView, TemplateView, DetailView, UpdateView
from django.utils.translation import gettext as _
from django.http import Http404, HttpResponseRedirect
from django.core.paginator import InvalidPage

from rest_framework import viewsets

from .forms import UserForm, HomeForm, imageformset
from .serializers import UserSerializer, HomeSerializer
from .models import User, Home, HomeImage


class HomeView(TemplateView, ListView):
    template_name = 'users/home.html'
    model = User
    queryset = User.objects.all()
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        self.object_list = User.objects.all()
        user_queryset = User.objects.all()
        homes_queryset = Home.objects.all()
        page_size = self.paginate_by
        user_paginator, user_page, user_queryset, user_is_paginated = self.paginate_queryset(user_queryset, page_size, "user_page")
        home_paginator, home_page, home_queryset, home_is_paginated = self.paginate_queryset(homes_queryset, page_size, "home_page")
        context = {
            'user_paginator': user_paginator,
            'user_page': user_page,
            'user_is_paginated': user_is_paginated,
            'user_queryset': user_queryset,
            'home_paginator': home_paginator,
            'home_page': home_page,
            'home_is_paginated': home_is_paginated,
            'home_queryset': home_queryset
        }

        context.update(kwargs)
        return context

    def paginate_queryset(self, queryset, page_size, page_kwarg):
        """Paginate the queryset, if needed."""
        paginator = self.get_paginator(
            queryset, page_size, orphans=self.get_paginate_orphans(),
            allow_empty_first_page=self.get_allow_empty())
        page = self.kwargs.get(page_kwarg) or self.request.GET.get(page_kwarg) or 1
        try:
            page_number = int(page)
        except ValueError:
            if page == 'last':
                page_number = paginator.num_pages
            else:
                raise Http404(_('Page is not “last”, nor can it be converted to an int.'))
        try:
            page = paginator.page(page_number)
            return (paginator, page, page.object_list, page.has_other_pages())
        except InvalidPage as e:
            raise Http404(_('Invalid page (%(page_number)s): %(message)s') % {
                'page_number': page_number,
                'message': str(e)
            })


class UserViewSet(viewsets.ModelViewSet):
    model = User
    serializer_class = UserSerializer
    queryset = User.objects.all()
    allowed_methods = "GET", "POST", "PATCH", "DELETE"


class HomeViewSet(viewsets.ModelViewSet):
    model = Home
    serializer_class = HomeSerializer
    queryset = Home.objects.all()
    allowed_methods = "GET", "POST", "PATCH", "DELETE"


class UserView(ListView):
    model = User
    paginate_by = 10
    template_name = 'users/users_list.html'
    queryset = User.objects.all()


class UserDetailView(DetailView):
    model = User
    slug_field = 'id'


class UserUpdateView(UpdateView):
    model = User
    slug_field = 'id'
    form_class = UserForm

    def get_success_url(self):
        self.success_url = reverse('users')
        return self.success_url


class HomeUpdateView(UpdateView):
    model = Home
    slug_field = 'id'
    form_class = HomeForm

    def get_success_url(self):
        self.success_url = reverse('homes-update', args=(self.object.id,))
        return self.success_url

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['img_form'] = imageformset(self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['img_form'] = imageformset(instance=self.object)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        home_form = self.get_form(form_class)
        img_form = imageformset(self.request.POST, self.request.FILES, instance=self.object)

        if (home_form.is_valid() and img_form.is_valid()):
            return self.form_valid(home_form, img_form)
        else:
            return self.form_invalid(home_form, img_form)

    def form_valid(self, home_form, img_form):
        self.object = home_form.save()
        img_form.instance = self.object
        img_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, home_form, img_form):
        return self.render_to_response(self.get_context_data(home_form=home_form,
                                                             img_form=img_form))


class HomesView(ListView):
    model = Home
    paginate_by = 10
    template_name = 'users/homes_list.html'
    queryset = Home.objects.all()

    def get_queryset(self):
        user_id = self.request.GET.get("user_id")
        queryset = super().get_queryset().filter()
        if user_id:
            queryset = queryset.filter(user_id=user_id)
        return queryset


class ImageListView(ListView):
    model = HomeImage
    queryset = HomeImage.objects.all()
    template_name = "users/home_images.html"

    def get_queryset(self):
        home_id = self.request.GET.get("home_id")
        queryset = super().get_queryset().filter()
        if home_id:
            queryset = queryset.filter(home_id=home_id)
        return queryset

templates/users/home.html
{% extends 'base.html' %}

{% block content %}

    <div class="parallax-container">
        <div class="parallax"><img src="static/background2.jpg"></div>
    </div>
    <div class="section white">
        <div class="row container">
            <h2 class="header">Home Page</h2>
            <p class="grey-text text-darken-3 lighten-3"></p>
        </div>
    </div>
    <h2 class="header">Users</h2>

    <table class="centered">
        <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Age</th>
        </tr>
        </thead>

        <tbody>
        {% for user in user_queryset %}
            <tr>

                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.age }}</td>
            </tr>
        {% endfor %}
        </tbody>

    </table>
    {% if user_is_paginated %}
        <ul class="pagination">
            {% if user_page.has_previous %}
                <li class="waves-effect">
                    <span><a href="{% url_replace request 'user_page' user_page.previous_page_number %}">Previous</a></span>
                </li>
            {% endif %}
            <li class="waves-effect">
                <span>Page {{ user_page.number }} of {{ user_page.paginator.num_pages }}.</span>
            </li>

            {% if user_page.has_next %}
                <li class="waves-effect">
                    <span><a href="{% url_replace request 'user_page' user_page.next_page_number %}">Next</a></span>
                </li>
            {% endif %}
        </ul>
    {% endif %}


    <h2 class="header">Homes</h2>
    <table class="centered">
        <thead>
        <tr>
            <th>Title</th>
            <th>Location</th>
            <th>Land sqm</th>
            <th>Place sqm</th>
            <th>Bedrooms</th>
        </tr>
        </thead>

        <tbody>
        {% for home in home_queryset %}
            <tr>
                <td>{{ home.title }}</td>
                <td>{{ home.location }}</td>
                <td>{{ home.land_sqm }}</td>
                <td>{{ home.place_sqm }}</td>
                <td>{{ home.bedrooms }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
     {% if home_is_paginated %}
        <ul class="pagination">
            {% if home_page.has_previous %}
                <li class="waves-effect">
                    <span><a href="{% url_replace request 'home_page' home_page.previous_page_number %}">Previous</a></span>
                </li>
            {% endif %}
            <li class="waves-effect">
                <span>Page {{ home_page.number }} of {{ home_page.paginator.num_pages }}.</span>
            </li>

            {% if home_page.has_next %}
                <li class="waves-effect">
                        <span><a href="{% url_replace request 'home_page' home_page.next_page_number %}">Next</a></span>
                </li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock content %}

templates/users/home_form.html
{% extends "base.html" %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    {{ img_form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock content %}

templates/users/home_images.html
{% extends 'base.html' %}

{% block content %}
 <h2 class="header">Home Images</h2>
     {% for image in object_list %}
            <img  src="{{ image.image.url }}" alt="image">
         <br>
     {% endfor %}


{% endblock content%}

templates/users/homes_list.html
{% extends 'base.html' %}

{% block content %}
<table class="centered">
        <thead>
          <tr>
              <th>User</th>
              <th>Title</th>
              <th>Location</th>
              <th>Land sqm</th>
              <th>Place sqm</th>
              <th>Bedrooms</th>
              <th>Images</th>
              <th></th>
          </tr>
        </thead>
        <tbody>
        {% for home in object_list %}
        <tr>
            <td>{{ home.user.email }}</td>
            <td>{{ home.title }}</td>
            <td>{{ home.location }}</td>
            <td>{{ home.land_sqm }}</td>
            <td>{{ home.place_sqm }}</td>
            <td>{{ home.bedrooms }}</td>
            <td><a href="{% url 'home_images' home_id=home.id%}"><img  style="max-height:10%; max-width:10%" src="{{ home.homeimage_set.all.first.image.url }}" alt="image"></a></td>
            <td><a href="{% url 'homes-update' pk=user.pk %}" class="waves-effect waves-light btn">Edit</a></td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
     {% include "pagination.html" %}
{% endblock content %}

templates/users/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<p>{{ object.first_name }}</p>
<p>{{ object.last_name }}</p>
<p>{{ object.email }}</p>
<p>{{ object.age }}</p>


{% endblock content%}

templates/users/user_form.html
{% extends "base.html" %}

{% block content %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock content %}

templates/users/users_list.html
{% extends 'base.html' %}
{% block content %}
<table class="centered">
        <thead>
          <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Age</th>
              <th></th>
          </tr>
        </thead>

        <tbody>
        {% for user in object_list %}
        <tr>
            <td><a href="{% url 'homes' %}?user_id={{ user.id }}">{{ user.first_name }}</a></td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.age }}</td>
            <td><a href="{% url 'users-update' pk=user.pk %}" class="waves-effect waves-light btn">Edit</a></td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
 {% include "pagination.html" %}
{% endblock content %}